# Type Sync Script - Copies backend DTOs to frontend
# Usage: .\sync-types.ps1

$ErrorActionPreference = "Stop"

Write-Host "🔄 Syncing types from backend to frontend..." -ForegroundColor Cyan

# Paths
$sourceFile = "d:\worker_control\server\src\types\dtos.ts"
$targetDir = "d:\worker_control\client\lib\types"
$targetFile = "$targetDir\api.ts"

# Ensure target directory exists
if (!(Test-Path $targetDir)) {
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    Write-Host "✅ Created directory: $targetDir" -ForegroundColor Green
}

# Read source file
$content = Get-Content $sourceFile -Raw

# Remove Zod imports and validation code (frontend only needs types)
$content = $content -replace "import \{ z \} from 'zod';", ""
$content = $content -replace "export const \w+Schema = z\..+?;", ""

# Add frontend-specific header
$header = @"
/**
 * API Type Definitions
 * AUTO-GENERATED from server/src/types/dtos.ts
 * DO NOT EDIT THIS FILE DIRECTLY - Run sync-types.ps1 instead
 * Last synced: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
 */

"@

# Combine header and content
$finalContent = $header + $content

# Write to target
Set-Content -Path $targetFile -Value $finalContent -Encoding UTF8

Write-Host "✅ Types synced successfully!" -ForegroundColor Green
Write-Host "📁 Target: $targetFile" -ForegroundColor Gray
Write-Host ""
Write-Host "📝 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Import types in your React components:" -ForegroundColor Gray
Write-Host "      import type { EmployerResponse } from '@/lib/types/api'" -ForegroundColor Gray
Write-Host "   2. Use with API calls for type safety" -ForegroundColor Gray
Write-Host ""
